- name: Setup NodeJS repos
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Installing NodeJS
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: Add Roboshop user
  ansible.builtin.user:
    name: roboshop

- name: Removing previous app content
  ansible.builtin.file:
    path: "{{ APP_LOC }}"
    state: absent

- name: Creating app content
  ansible.builtin.file:
    path: "{{ APP_LOC }}"
    state: directory

- name: Fetching Extracting catalogue scripts
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/catalogue.zip
    dest: "{{ APP_LOC }}"
    remote_src: yes

- name: Install NodeJS dependencies
  community.general.npm:
    path: "{{ APP_LOC }}"
    state: present

- name: Copying catalogue service file
  ansible.builtin.copy:
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service

- name: Updating MongoDB host address
  ansible.builtin.replace:
    path: /etc/systemd/system/catalogue.service
    regexp: '<MONGODB-SERVER-IPADDRESS>'
    replace: 'mongodb-dev.learninguser.online'

- name: Reload service catalogue
  ansible.builtin.systemd:
    name: catalogue.service
    state: reloaded
    enabled: yes

- name: Copying MongoDB repo file
  ansible.builtin.copy:
    src: mongod.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Installing MongoDB
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: installed

- name: Load catalogue schema
  community.mongodb.mongodb_shell:
    login_host : "mongodb-dev.learninguser.online"
    file: '/app/schema/catalogue.js'
    idempotent: yes